name: Auto Deploy to EC2 with Docker Stack

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ubuntu

          # If the app-fastapi directory does not exist, create it and clone
          if [ ! -d "app-fastapi" ]; then
            echo "Creating app-fastapi directory and cloning repo..."
            mkdir -p app-fastapi
            cd app-fastapi
            git clone -b ${{ github.ref_name }} https://github.com/${{ github.repository }}.git .
          else
            echo "Repo exists. Pulling updates..."
            cd app-fastapi
            git reset --hard
            git pull origin ${{ github.ref_name }}
          fi
          
          # Debug: Check if files exist
          echo "Current directory: $(pwd)"
          echo "Files in directory:"
          ls -la
          
          # Check if docker-stack.yml exists
          if [ ! -f "docker-stack.yml" ]; then
            echo "ERROR: docker-stack.yml not found!"
            exit 1
          fi
          
          echo "docker-stack.yml found, proceeding with deployment..."
          
          # Check if user is in docker group, if not use sudo
          if docker ps > /dev/null 2>&1; then
            echo "Using docker without sudo"
            docker stack deploy -c docker-stack.yml app_stack
          else
            echo "Using docker with sudo"
            sudo docker stack deploy -c docker-stack.yml app_stack
          fi 